const fs = require('fs');
const path = require('path');
const dir = 'd:/project/cosmetic-shop/frontend/app/public/components/account';
const files = fs.readdirSync(dir).filter(f => f.endsWith('.tsx'));
const dict = {
  'Quản lý tài khoản': 'Account Management',
  'Hồ sơ của tôi': 'My Profile',
  'Sổ địa chỉ': 'Address Book',
  'Đơn hàng của tôi': 'My Orders',
  'Sản phẩm yêu thích': 'Favorite Products',
  'Đã xem gần đây': 'Recently Viewed',
  'Đăng xuất': 'Logout',
  'Chào bạn': 'Hello',
  'Kho voucher': 'Vouchers',
  'Quản lý đơn hàng & yêu thích': 'Orders & Favorites',
  'Sản phẩm đã xem': 'Viewed Products',
  'Khám phá cửa hàng và xem các sản phẩm bạn yêu thích': 'Discover the store and view your favorite products',
  'Khám phá sản phẩm': 'Discover products',
  'Xóa khỏi lịch sử': 'Remove from history',
  'Xóa toàn bộ lịch sử?': 'Clear all history?',
  'Xóa sản phẩm khỏi lịch sử?': 'Remove product from history?',
  'Toàn bộ lịch sử xem sẽ bị xóa vĩnh viễn. Hành động này không thể hoàn tác.': 'All viewed history will be permanently deleted. This action cannot be undone.',
  'Sản phẩm này sẽ bị xóa khỏi lịch sử xem của bạn.': 'This product will be removed from your viewed history.',
  'Xóa tất cả': 'Clear all',
  'Lịch sử duyệt sản phẩm của bạn': 'Your browsing history',
  'Xóa lịch sử': 'Clear history',
  'Chưa có sản phẩm nào trong lịch sử': 'No products in history yet',
  'Xóa': 'Remove',
  'Hạng thành viên': 'Membership Tier',
  'Hạng được tính từ tổng chi tiêu đơn hàng hoàn thành': 'Tier is calculated from total completed order spending',
  'Hạng hiện tại': 'Current Tier',
  'Tổng chi tiêu': 'Total Spent',
  'đơn hoàn thành': 'completed orders',
  'Chi tiêu': 'Spent',
  'Đơn hoàn thành': 'Completed orders',
  'Ưu đãi hạng': 'Tier benefits',
  'Chưa có': 'None',
  'Tiến trình thăng hạng': 'Tier progress',
  'Chi thêm': 'Spend more',
  'để đạt hạng': 'to reach',
  'Chúc mừng! Bạn đã đạt hạng cao nhất 🎉': 'Congratulations! You have reached the highest tier 🎉',
  'Cảm ơn bạn đã đồng hành cùng GlowUp Beauty': 'Thank you for being with GlowUp Beauty',
  'Quyền lợi theo hạng': 'Benefits by tier',
  'Hạng': 'Tier',
  'Chi tiêu tối thiểu': 'Minimum spent',
  'Giảm giá đơn hàng': 'Order discount',
  'Hiện tại': 'Current',
  'Mặc định': 'Default',
  'triệu₫': 'M ₫',
  'Giảm giá áp dụng tự động khi thanh toán, không cộng thêm với mã': 'Discounts apply automatically at checkout, cannot be combined with promo codes',
  'giảm giá.': '.',
  'Không thể tải thông tin hạng thành viên': 'Failed to load membership tier information',
  'Khả dụng': 'Available',
  'Đã sử dụng': 'Used',
  'Hết hạn': 'Expired',
  'Mã giảm giá đã lưu của bạn': 'Your saved vouchers',
  'Bạn chưa có mã khả dụng. Hãy lưu mã từ trang chủ!': 'You have no available vouchers. Save vouchers from the homepage!',
  'Bạn chưa sử dụng mã giảm giá nào.': "You haven't used any vouchers.",
  'Không có mã giảm giá đã hết hạn.': 'No expired vouchers.',
  'Cập nhật địa chỉ thành công': 'Address updated successfully',
  'Thêm địa chỉ thành công': 'Address added successfully',
  'Lưu địa chỉ thất bại': 'Failed to save address',
  'Bạn có chắc muốn xóa địa chỉ này?': 'Are you sure you want to delete this address?',
  'Đã xóa địa chỉ': 'Address deleted',
  'Xóa thất bại': 'Failed to delete',
  'Cập nhật địa chỉ': 'Update Address',
  'Địa chỉ mới': 'New Address',
  'Tỉnh / Thành phố': 'Province / City',
  '-- Chọn tỉnh/thành --': '-- Select province/city --',
  'Quận / Huyện': 'District',
  'Đang tải...': 'Loading...',
  '-- Chọn quận/huyện --': '-- Select district --',
  'Phường / Xã': 'Ward',
  '-- Chọn phường/xã --': '-- Select ward --',
  'Số nhà / Tên đường': 'Street Address',
  'VD: 123 Nguyễn Huệ': 'Ex: 123 Nguyen Hue',
  'Đặt làm địa chỉ mặc định': 'Set as default address',
  'Đang lưu...': 'Saving...',
  'Lưu địa chỉ': 'Save Address',
  'Hủy bỏ': 'Cancel',
  'Địa chỉ giao hàng đã lưu của bạn': 'Your saved shipping addresses',
  'Thêm địa chỉ': 'Add Address',
  'Bạn chưa có địa chỉ nào trong sổ.': "You don't have any addresses yet.",
  'Thêm địa chỉ để thanh toán nhanh hơn.': 'Add an address for faster checkout.',
  'Ảnh quá lớn. Tối đa 1.5 MB.': 'Image too large. Max 1.5 MB.',
  'Cập nhật ảnh đại diện thành công!': 'Avatar updated successfully!',
  'Có lỗi khi cập nhật ảnh.': 'Error updating avatar.',
  'Cập nhật thông tin thành công!': 'Information updated successfully!',
  'Có lỗi khi cập nhật thông tin.': 'Error updating information.',
  'Chưa cập nhật': 'Not updated',
  'Thông tin tài khoản': 'Account Information',
  'Quản lý thông tin cá nhân và bảo mật': 'Manage personal information and security',
  'Ảnh đại diện': 'Avatar',
  'Định dạng JPEG, PNG, WEBP. Tối đa 1.5MB.': 'JPEG, PNG, WEBP format. Max 1.5MB.',
  'Đang tải ảnh...': 'Uploading image...',
  'Thay đổi ảnh': 'Change avatar',
  'Thông tin cá nhân': 'Personal Information',
  'Họ và tên': 'Full Name',
  'Số điện thoại': 'Phone Number',
  'Chưa có số điện thoại': 'No phone number',
  'Giới tính': 'Gender',
  'Nam': 'Male',
  'Nữ': 'Female',
  'Khác': 'Other',
  'Ngày sinh': 'Date of Birth',
  'Đang cập nhật...': 'Updating...',
  'Cập nhật': 'Update',
  'Tất cả': 'All',
  'Chờ xác nhận': 'Pending',
  'Đang giao': 'Delivering',
  'Hoàn thành': 'Completed',
  'Đã hủy': 'Cancelled',
  'Tìm kiếm đơn hàng...': 'Search orders...',
  'Đơn hàng của bạn': 'Your Orders',
  'Theo dõi và quản lý lịch sử mua hàng': 'Track and manage purchase history',
  'Chưa có đơn hàng nào': 'No orders yet',
  'Bạn chưa có đơn hàng nào trong trạng thái này.': 'You have no orders in this status.',
  'Mã đơn': 'Order ID',
  'Ngày đặt': 'Order Date',
  'Trạng thái': 'Status',
  'Tổng tiền': 'Total Amount',
  'Chi tiết': 'Details',
  'Mua lại': 'Buy Again',
  'sản phẩm khác': 'other products',
  'Thành tiền': 'Total',
  'Hủy đơn hàng': 'Cancel Order',
  'Đã hủy đơn hàng thành công': 'Order cancelled successfully',
  'Hủy đơn hàng thất bại': 'Failed to cancel order',
  'Chi tiết đơn hàng': 'Order Details',
  'Giao hàng tiêu chuẩn': 'Standard Shipping',
  'Giao hàng nhanh': 'Express Shipping',
  'Tiền mặt khi nhận hàng (COD)': 'Cash on Delivery (COD)',
  'Đã thanh toán (VNPay)': 'Paid (VNPay)',
  'Chờ thanh toán': 'Pending Payment',
  'Thông tin nhận hàng': 'Shipping Information',
  'Phương thức giao hàng': 'Shipping Method',
  'Phương thức thanh toán': 'Payment Method',
  'Sản phẩm': 'Products',
  'Tạm tính': 'Subtotal',
  'Phí giao hàng': 'Shipping Fee',
  'Giảm giá': 'Discount',
  'Sản phẩm bạn đã thích': 'Products you liked',
  'Bạn chưa thích sản phẩm nào.': "You haven't liked any products yet.",
  'Khám phá ngay': 'Discover Now',
  'Không tìm thấy chi tiết đơn hàng': 'Order details not found',
  'Mặc định': 'Default',
  'Chỉnh sửa': 'Edit',
  'Xóa': 'Delete',
  'Hoạt động gần nhất': 'Recent activity',
  'Không có dữ liệu hiển thị': 'No data to display',
  'Giao hàng tận nơi': 'Home Delivery'
};

for (const file of files) {
  const p = path.join(dir, file);
  let content = fs.readFileSync(p, 'utf8');
  for (const [vi, en] of Object.entries(dict)) {
    content = content.split(vi).join(en);
  }
  fs.writeFileSync(p, content);
}
console.log('Done translating');
